export const FIRST_NAMES = [
  'Alejandra', 'Alejandro', 'Alicia', 'Alonso', 'Álvaro', 'Amanda', 'Ana', 'Andrea',
  'Andrés', 'Ángel', 'Antonia', 'Antonio', 'Beatriz', 'Benjamín', 'Blanca', 'Bruno',
  'Camila', 'Carlos', 'Carmen', 'Carolina', 'Catalina', 'Cecilia', 'César', 'Clara',
  'Claudia', 'Cristian', 'Cristina', 'Daniel', 'Daniela', 'David', 'Diana', 'Diego',
  'Dolores', 'Eduardo', 'Elena', 'Elisa', 'Emilia', 'Emilio', 'Enrique', 'Ernesto',
  'Esteban', 'Eva', 'Fabián', 'Felipe', 'Fernanda', 'Fernando', 'Francisco', 'Gabriel',
  'Gabriela', 'Gloria', 'Gonzalo', 'Guadalupe', 'Guillermo', 'Gustavo', 'Helena', 'Hernán',
  'Hugo', 'Ignacio', 'Inés', 'Irene', 'Isabel', 'Iván', 'Jaime', 'Javier',
  'Jimena', 'Joaquín', 'Jorge', 'José', 'Josefina', 'Juan', 'Juana', 'Julia',
  'Julián', 'Julieta', 'Laura', 'Leonardo', 'Liliana', 'Lorenzo', 'Lucía', 'Luis',
  'Luisa', 'Manuel', 'Manuela', 'Marcela', 'Marco', 'Marcos', 'Margarita', 'María',
  'Mariana', 'Marina', 'Mario', 'Marta', 'Martín', 'Mateo', 'Matías', 'Mercedes',
  'Miguel', 'Mónica', 'Natalia', 'Nicolás', 'Noelia', 'Nora', 'Olga', 'Oscar',
  'Pablo', 'Patricia', 'Paula', 'Pedro', 'Pilar', 'Rafael', 'Raúl', 'Rebeca',
  'Ricardo', 'Roberto', 'Rocío', 'Rodrigo', 'Rosa', 'Rubén', 'Salvador', 'Samuel',
  'Sandra', 'Santiago', 'Sara', 'Sebastián', 'Silvia', 'Sofía', 'Sonia', 'Teresa',
  'Tomás', 'Valentina', 'Valeria', 'Vicente', 'Víctor', 'Victoria', 'Virginia', 'Xavier',
  'Yolanda', 'Adriana', 'Agustín', 'Bárbara', 'Berta', 'Camilo', 'Dario', 'Elvira',
  'Estela', 'Fátima', 'Graciela', 'Héctor', 'Hilda', 'Ivana', 'Jessica', 'Kevin',
  'Lorena', 'Luciano', 'Magdalena', 'Mauricio', 'Nadia', 'Omar', 'Paola', 'Ramón',
  'Renata', 'Sergio', 'Tamara', 'Ulises', 'Verónica', 'Walter', 'Yamila', 'Zoe',
];

export const LAST_NAMES = [
  'Acosta', 'Aguilar', 'Alonso', 'Álvarez', 'Arias', 'Benítez', 'Blanco', 'Bravo',
  'Cabrera', 'Calvo', 'Campos', 'Cano', 'Cárdenas', 'Castro', 'Chávez', 'Cortés',
  'Cruz', 'Delgado', 'Díaz', 'Domínguez', 'Duarte', 'Escobar', 'Espinoza', 'Fernández',
  'Figueroa', 'Flores', 'Franco', 'Fuentes', 'García', 'Giménez', 'Gómez', 'González',
  'Guerrero', 'Gutiérrez', 'Guzmán', 'Hernández', 'Herrera', 'Iglesias', 'Jiménez', 'León',
  'López', 'Lorenzo', 'Luna', 'Maldonado', 'Marín', 'Márquez', 'Martín', 'Martínez',
  'Medina', 'Méndez', 'Mendoza', 'Molina', 'Montero', 'Morales', 'Moreno', 'Muñoz',
  'Navarro', 'Núñez', 'Ortega', 'Ortiz', 'Pacheco', 'Paredes', 'Paz', 'Peña',
  'Pérez', 'Prieto', 'Ramírez', 'Ramos', 'Ríos', 'Rivas', 'Rivera', 'Rojas',
  'Romero', 'Ruiz', 'Salazar', 'Sánchez', 'Sandoval', 'Santos', 'Serrano', 'Silva',
  'Soto', 'Suárez', 'Torres', 'Valdez', 'Vargas', 'Vásquez', 'Vega', 'Velázquez',
  'Vera', 'Vidal', 'Villalobos', 'Villanueva', 'Zamora', 'Zúñiga',   'Araya', 'Bustos',
  'Contreras', 'Farías', 'Gallardo', 'Henríquez', 'Jara', 'Lagos', 'Miranda',
  'Olivares', 'Pizarro', 'Quiroga', 'Reyes', 'Sepúlveda', 'Tapia', 'Ulloa', 'Valenzuela',
  'Yáñez', 'Alarcón', 'Cáceres', 'Godoy', 'Ibarra', 'Juárez', 'Lara',
];
